on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: ["386", amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: "linux"
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz"
        project_path: "./geowall"
        binary_name: "geowall"
        ldflags: "-s -w -X main.Version=${RELEASE_TAG}"
        executable_compression: "upx -qq --brute"
